version: '3.3'
services:
  post_db:    
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit-backend: 
        aliases: 
          - post_db
          - comment_db
  ui:
    image: '${USERNAME}/ui:${UI_VERSION}'
    ports:
      - '${PORT_HOST}:${PORT_CONTAINER}/tcp'
    networks:
      reddit-frontend: 
        aliases: 
          - ui
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      reddit-frontend: 
        aliases: 
          - post
      reddit-backend: 
        aliases: 
          - post
  comment:    
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      reddit-frontend: 
        aliases: 
          - comment
      reddit-backend: 
        aliases: 
          - comment

  prometheus:
    image: ${USERNAME}/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      reddit-frontend: 
        aliases: 
          - prometheus
      reddit-backend: 
        aliases: 
          - prometheus
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      reddit-backend:
        aliases:
          - node-exporter
  mongodb_exporter:
    image: ${USERNAME}/mongodb_exporter:latest
    networks:
      reddit-backend:
        aliases:
          - mongodb_exporter
  cloudprober:
    image: ${USERNAME}/cloudprober:latest
    networks:
      reddit-frontend:
        aliases:
          - cloudprober

volumes:
  post_db:
  prometheus_data:

networks:
  reddit-frontend:
  reddit-backend:
