version: '3.3'
services:
  post_db:    
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit-backend: 
        aliases: 
          - post_db
          - comment_db

  ui:
    image: '${USER_NAME}/ui:${UI_VERSION}'
    ports:
      - '${PORT_HOST}:${PORT_CONTAINER}/tcp'
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      reddit-frontend: 
        aliases: 
          - ui
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    
  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      reddit-frontend: 
        aliases: 
          - post
      reddit-backend: 
        aliases: 
          - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:    
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    environment:
     - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      reddit-frontend: 
        aliases: 
          - comment
      reddit-backend: 
        aliases: 
          - comment


volumes:
  post_db:

networks:
  reddit-frontend:
  reddit-backend:
