version: '3.3'
services:
  post_db:    
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit-backend: 
        aliases: 
          - db
  ui:    
    build: ./ui
    image: '${USERNAME}/ui:${UI_VERSION}'
    ports:
      - '${PORT_HOST}:${PORT_CONTAINER}/tcp'
    networks:
      reddit-frontend: 
        aliases: 
          - ui
  post:    
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      reddit-frontend: 
        aliases: 
          - post
      reddit-backend: 
        aliases: 
          - post
  comment:    
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      reddit-frontend: 
        aliases: 
          - comment
      reddit-backend: 
        aliases: 
          - comment

volumes:
  post_db:

networks:
  reddit-frontend:
  reddit-backend:
